name: trophies
version: '1.0-SNAPSHOT'
main: me.HolyMakkaroni79.trophies.Trophies
api-version: '1.21'
authors: [ HolyMakkaroni79 ]

commands:
  trophy:
    description: To open the menu where u can found the trophies
    permission: trophy
  trophytest:
    permission: trophy

permissions:
  trophy:
    description: Do the permission stuff
    default: true
